name: Rust

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master

      - name: Run tests on windows
        if: matrix.os == 'windows-latest'
        run: cargo test --verbose

      - name: Run tests on *nix
        run: cargo test --verbose
        if: matrix.os != 'windows-latest'
